services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: customer_billing_portal
    networks:
      - app

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    networks:
      - app
    ports:
      - '8080:8080'

  billing-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    networks:
      - app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - adminer
    command: [sh, -c, 'npm run start:dev']
    volumes:
      - .:/app:delegated
      - /app/node_modules

networks:
  app:
